<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBOHMaJx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBOHMaJx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBOHMaJx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBOHMaJx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBOHMaJx\App_KernelDevDebugContainer([
    'container.build_hash' => 'BOHMaJx',
    'container.build_id' => '6b21e8e7',
    'container.build_time' => 1621430880,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBOHMaJx');
