<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTdpyf9P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTdpyf9P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTdpyf9P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTdpyf9P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTdpyf9P\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tdpyf9P',
    'container.build_id' => '8caad97a',
    'container.build_time' => 1621496061,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTdpyf9P');
