<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHejOtXx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHejOtXx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHejOtXx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHejOtXx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHejOtXx\App_KernelDevDebugContainer([
    'container.build_hash' => 'HejOtXx',
    'container.build_id' => 'c3dc90cb',
    'container.build_time' => 1622018590,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHejOtXx');
