<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'accueil' => [[], ['_controller' => 'App\\Controller\\AutresElementsController::index'], [], [['text', '/']], [], []],
    'portail' => [[], ['_controller' => 'App\\Controller\\AutresElementsController::portail'], [], [['text', '/portail']], [], []],
    'mention' => [[], ['_controller' => 'App\\Controller\\AutresElementsController::mention'], [], [['text', '/mention']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\AutresElementsController::contact'], [], [['text', '/contact']], [], []],
    'passage_a_gue_index' => [[], ['_controller' => 'App\\Controller\\PassageController::index'], [], [['text', '/passage/']], [], []],
    'recherche' => [[], ['_controller' => 'App\\Controller\\PassageController::recherche'], [], [['text', '/passage/recherche']], [], []],
    'creation' => [[], ['_controller' => 'App\\Controller\\PassageController::creation'], [], [['text', '/passage/creation']], [], []],
    'passage_a_gue_show' => [['id'], ['_controller' => 'App\\Controller\\PassageController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/passage']], [], []],
    'passage_a_gue_edit' => [['id'], ['_controller' => 'App\\Controller\\PassageController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/passage']], [], []],
    'passage_a_gue_delete' => [['id'], ['_controller' => 'App\\Controller\\PassageController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/passage']], [], []],
    'app_registration' => [[], ['_controller' => 'App\\Controller\\SecurityController::registration'], [], [['text', '/inscription']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'parametrage' => [[], ['_controller' => 'App\\Controller\\SecurityController::parametrage'], [], [['text', '/parametrage']], [], []],
    'profil' => [[], ['_controller' => 'App\\Controller\\SecurityController::profil'], [], [['text', '/profil']], [], []],
];
